spring.datasource.url=jdbc:postgresql://db:5432/penguins
spring.datasource.username=penguins
spring.datasource.password=penguins
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
